---
name: Continuous deployment

on:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  publish-to-cargo:
    name: Publishing to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Get build cache
        uses: Swatinem/rust-cache@v2
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_API_KEY }} --allow-dirty
